version: "3.9"

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: fc_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
volumes:
  pgdb: